name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-extension:
    name: Test Extension
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: 'spring-test-insight-extension/pom.xml'

      - name: Test extension
        working-directory: spring-test-insight-extension
        run: ./mvnw verify

  test-maven-demos:
    name: Test Gradle Demo Projects
    runs-on: ubuntu-latest
    needs: test-extension
    strategy:
      fail-fast: false
      matrix:
        demo:
          - spring-boot-3.4-maven
          - spring-boot-3.5-maven
          - spring-boot-3.5-maven-failsafe-parallel
          - spring-boot-3.5-maven-junit-parallel

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: '${{ matrix.demo }}/pom.xml'

      - name: Install extension to local repository
        working-directory: spring-test-insight-extension
        run: ./mvnw clean install -DskipTests

      - name: Build demo project
        id: build-demo
        continue-on-error: true
        working-directory: demo/${{ matrix.demo }}
        run: ./mvnw verify

      - name: Report demo status
        if: always()
        run: |
          echo "### Test results for ${{ matrix.demo }}"
          if [ "${{ steps.build-demo.outcome }}" == "success" ]; then
            echo "✅ Tests passed"
          else
            echo "❌ Tests failed"
          fi

      - name: Upload demo test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: demo-test-results-${{ matrix.demo }}
          path: demo/${{ matrix.demo }}/target

  test-gradle-demos:
    name: Test Gradle Demo Projects
    runs-on: ubuntu-latest
    needs: test-extension
    strategy:
      fail-fast: false
      matrix:
        demo:
          - spring-boot-3.5-gradle

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
          cache-dependency-path: '${{ matrix.demo }}/build.gradle'

      - name: Install extension to local repository
        working-directory: spring-test-insight-extension
        run: ./mvnw clean install -DskipTests

      - name: Build demo project
        id: build-demo
        continue-on-error: true
        working-directory: demo/${{ matrix.demo }}
        run: ./gradlew build

      - name: Report demo status
        if: always()
        run: |
          echo "### Test results for ${{ matrix.demo }}"
          if [ "${{ steps.build-demo.outcome }}" == "success" ]; then
            echo "✅ Tests passed"
          else
            echo "❌ Tests failed"
          fi

      - name: Upload demo test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: demo-test-results-${{ matrix.demo }}
          path: |
            demo/${{ matrix.demo }}/build

  summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [test-extension, test-maven-demos, test-gradle-demos]
    if: always()

    steps:
      - name: Test Results Summary
        run: |
          echo "## Test Results Summary"
          echo ""
          echo "### Extension Tests"
          if [ "${{ needs.test-extension.result }}" == "success" ]; then
            echo "✅ Extension tests passed"
          else
            echo "❌ Extension tests failed"
          fi
          echo ""
          echo "### Demo Projects"
          echo "Demo tests status: ${{ needs.test-demos.result }}"
          echo ""
          echo "Note: Individual demo project results can be found in the workflow run details."

      - name: Check critical failures
        if: needs.test-extension.result == 'failure'
        run: |
          echo "Critical failure: Extension tests failed"
          exit 1

      - name: Final status
        run: |
          if [ "${{ needs.test-extension.result }}" == "success" ]; then
            echo "✅ Core extension tests passed - build is acceptable"
            echo "Check individual demo results in the matrix job above"
          else
            echo "Build failed due to extension test failures"
            exit 1
          fi
