name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string
      nextVersion:
        description: 'Next version after release (-SNAPSHOT will be added automatically)'
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      NEXT_DEV_VERSION: ${{ github.event.inputs.nextVersion }}-SNAPSHOT

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw -Ppublication

      - name: Run JReleaser
        uses: jreleaser/release-action@v2
        with:
          arguments: 'full-release --git-root-search'
          version: 1.14.0
        env:
          JRELEASER_PROJECT_VERSION: ${{ github.event.inputs.version }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.MAVEN_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.MAVEN_GPG_SECRET_KEY }}
          JRELEASER_NEXUS2_MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          JRELEASER_NEXUS2_MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

      - name: Set next development version in pom.xml
        run: ./mvnw --batch-mode versions:set -DnewVersion=$NEXT_DEV_VERSION

      - name: Update JReleaser project.version
        run: 'sed -i "3s/version: .*/version: $NEXT_DEV_VERSION/" jreleaser.yml'

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.JRELEASER_GITHUB_TOKEN }}
          message: prepare for next development version $NEXT_DEV_VERSION
          tags: true
